import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from '@/components/ui/toaster';
import Script from "next/script";
import NavigationLoader from "@/components/NavigationLoader";


// ⭐ Add these
import ReviewChecker from "@/components/ReviewChecker";
import ReviewModal from "@/components/ReviewModal";
import NotificationSocket from "@/components/notifications/NotificationSocket";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tuitions time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>

          {/* 🔥 GLOBAL REVIEW SYSTEM  */}
          <ReviewChecker />
          <ReviewModal />
          <NotificationSocket />

           <NavigationLoader />
          {/* MAIN PAGE CONTENT */}
          {children}

          {/* Razorpay */}
          <Script
            src="https://checkout.razorpay.com/v1/checkout.js"
            strategy="afterInteractive"
          />


          <Toaster />

        </ReduxProvider>
      </body>
    </html>
  );
}
