import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "@/components/ui/toaster";
import Script from "next/script";
import NavigationLoader from "@/components/NavigationLoader";

// ⭐ Add these
import ReviewChecker from "@/components/ReviewChecker";
import ReviewModal from "@/components/ReviewModal";
import NotificationSocket from "@/components/notifications/NotificationSocket";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tuitions time",
  description: "Generated by create next app",
  verification: {
    google: "S3Ffj-pDtENu7NR4ArgiMIomUiNeZ87Dg8A0PCy1kws",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          {/* 🔥 GLOBAL REVIEW SYSTEM  */}
          <ReviewChecker />
          <ReviewModal />
          <NotificationSocket />

          <NavigationLoader />
          {/* MAIN PAGE CONTENT */}
          {children}

          {/* Razorpay */}
          <Script
            src="https://checkout.razorpay.com/v1/checkout.js"
            strategy="afterInteractive"
          />

          {/* Google Analytics */}
          <Script
            src="https://www.googletagmanager.com/gtag/js?id=G-3PFRYR2DR4"
            strategy="afterInteractive"
          />
          <Script id="google-analytics" strategy="afterInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-3PFRYR2DR4');
              console.log('Google Analytics initialized: G-3PFRYR2DR4');
            `}
          </Script>

          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
