export type FAQ = {
  question: string;
  answer: string;
};

export const faqs: FAQ[] = [
  { question: "How can I find the best home tutor near me?", answer: "Tuitionstime connects students with verified and experienced home tutors across India." },
  { question: "Do you offer online tuition classes?", answer: "Yes. We provide live online classes for all subjects from Nursery to Graduation." },
  { question: "Can I book a free demo class before enrolling?", answer: "Yes. Students can attend a free demo class before choosing a tutor." },
  { question: "Which subjects do your tutors teach?", answer: "Maths, Science, English, Hindi, Commerce, Computer Science, Social Science, Languages, and many more." },
  { question: "Which boards do you cover?", answer: "CBSE, ICSE, State Boards, IB, IGCSE, and other recognized curricula." },
  { question: "Which competitive exams do you prepare students for?", answer: "JEE, NEET, CUET, Olympiads, NTSE, SSC, Banking, and other competitive exams." },
  { question: "Are all tutors verified?", answer: "Yes. Every tutor completes a verification process before joining Tuitionstime." },
  { question: "How do I choose the right tutor?", answer: "Compare tutor profiles, qualifications, experience, and reviews before booking a demo." },
  { question: "Can I change my tutor if needed?", answer: "Yes. We help students find another suitable tutor if required." },
  { question: "Is home tuition available in my city?", answer: "Home tuition is available in many cities across India, subject to tutor availability." },
  { question: "Can I hire a tutor for only one subject?", answer: "Yes. You can choose one or multiple subjects." },
  { question: "Do you provide female home tutors?", answer: "Yes. Female tutors are available based on your preference and location." },
  { question: "Can I choose my class timings?", answer: "Yes. Flexible schedules are available." },
  { question: "Are weekend classes available?", answer: "Yes. Weekend and evening classes can be arranged." },
  { question: "What is the duration of each class?", answer: "Most classes are 60-90 minutes, depending on the student's needs." },
  { question: "Do tutors provide study materials?", answer: "Yes. Many tutors provide notes, worksheets, and practice papers." },
  { question: "Can tutors help with homework and assignments?", answer: "Yes. Tutors assist with homework, projects, and assignments." },
  { question: "Do you provide one-to-one tuition?", answer: "Yes. Personalized one-to-one learning is our specialty." },
  { question: "Do you offer group tuition?", answer: "Yes. Small group classes are also available." },
  { question: "Can parents monitor their child's progress?", answer: "Yes. Tutors provide regular performance updates." },
  { question: "Can parents communicate directly with tutors?", answer: "Yes. Parents can discuss progress, attendance, and learning goals." },
  { question: "Do you provide tutors for Nursery and Kindergarten?", answer: "Yes. We offer tutors for Nursery, LKG, UKG, and primary classes." },
  { question: "Do you provide tutors for college students?", answer: "Yes. Tutors are available for undergraduate and postgraduate courses." },
  { question: "Do you offer spoken English classes?", answer: "Yes. We provide Spoken English and communication skills training." },
  { question: "Do you provide coding and computer science tutors?", answer: "Yes. Tutors teach coding, programming, and computer science." },
  { question: "Can working professionals join Tuitionstime?", answer: "Yes. We offer learning programs for professionals as well." },
  { question: "How quickly can I get a tutor?", answer: "Usually within 24-48 hours, depending on availability." },
  { question: "Can I book more than one demo class?", answer: "Yes. Students can book multiple demo classes for different subjects to find the most suitable tutor for each learning requirement." },
  { question: "Can I reschedule a class?", answer: "Yes. Classes can be rescheduled with mutual agreement." },
  { question: "Do you offer holiday or vacation classes?", answer: "Yes. Holiday learning programs are available." },
  { question: "Do tutors prepare students for board exams?", answer: "Yes. Expert guidance is available for Class 10 and Class 12 board exams." },
  { question: "Do tutors prepare students for Olympiads?", answer: "Yes. We provide Olympiad and scholarship exam coaching." },
  { question: "Can I find tutors near my location?", answer: "Yes. We connect students with nearby tutors whenever possible." },
  { question: "Is Tuitionstime available across India?", answer: "Yes. We provide online and home tuition services across India." },
  { question: "How do online classes work?", answer: "Live interactive classes are conducted using secure online platforms." },
  { question: "What devices are needed for online classes?", answer: "A smartphone, tablet, laptop, or desktop with internet access." },
  { question: "Is there any registration fee for students?", answer: "No. Student registration on Tuitionstime is completely free. Students can register and submit their tuition requirements without any registration charges." },
  { question: "How can I become a tutor on Tuitionstime?", answer: "Register, complete the verification process, and start receiving student enquiries for online or home tuition." },
  { question: "What qualifications are required to become a tutor?", answer: "Graduates, postgraduates, professionals, and experienced teachers can apply." },
  { question: "Can tutors teach both online and offline?", answer: "Yes. Tutors can choose online tuition, home tuition, or both." },
  { question: "How do tutors receive student leads?", answer: "Tutors receive relevant student enquiries based on their subjects, experience, location, and availability." },
  { question: "Can tutors update their profile?", answer: "Yes. Tutors can update their qualifications, subjects, teaching experience, and availability at any time." },
  { question: "Is Tuitionstime safe and reliable?", answer: "Yes. We focus on verified tutors and a trusted learning experience for students and parents." },
  { question: "How is my personal information protected?", answer: "Your personal information is kept secure and handled according to our privacy practices." },
  { question: "What makes Tuitionstime different from other tutoring platforms?", answer: "Tuitionstime offers verified tutors, free student registration, free demo classes, personalized tutor matching, flexible learning options, and dedicated support." },
  { question: "Can I get tutors for special learning needs?", answer: "Yes. Subject to availability, we connect students with tutors experienced in supporting diverse learning needs." },
  { question: "How can I contact Tuitionstime?", answer: "You can contact us through our website, WhatsApp, email, or phone for any assistance." },
  { question: "What support does Tuitionstime provide after enrolment?", answer: "We assist with tutor coordination, class scheduling, and ongoing learning support." },
  { question: "Why should parents choose Tuitionstime?", answer: "Parents trust Tuitionstime for verified tutors, quality education, flexible schedules, regular progress updates, and reliable customer support." },
  { question: "Why should students choose Tuitionstime?", answer: "Tuitionstime offers personalized learning, expert tutors, flexible class timings, free student registration, free demo classes, and quality education to help every student succeed." },
];
